# Generated by Django 2.1.7 on 2020-04-14 19:12
import os

from django.db import migrations


def load_data_from_sql(filename):
    file_path = os.path.join(os.path.dirname(__file__), '../sql/', filename)
    sql_statement = open(file_path).read()
    return sql_statement


person_table = lambda: load_data_from_sql('person_table.sql')
create_procedure = lambda: load_data_from_sql('creator_procedure.sql')


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(person_table()),
        migrations.RunSQL(create_procedure())
    ]
